DROP USER C##JARDINERIA CASCADE;
DROP TABLESPACE JARDINERIA INCLUDING CONTENTS AND DATAFILES;
-- CONOCER LA RUTA DE LOS ARCHIVOS
SELECT  *  FROM DBA_DATA_FILES

-- CREATE TABLESPACE
CREATE TABLESPACE JARDINERIA
DATAFILE 'C:\APP\ESTUDIANTE\PRODUCT\21C\ORADATA\XE\jardineria_dat.dbf' SIZE 100M;

-- USER SQL
CREATE USER "C##JARDINERIA"
DEFAULT TABLESPACE "JARDINERIA"
TEMPORARY TABLESPACE "TEMP"
IDENTIFIED BY "Admin12345"
ACCOUNT UNLOCK ;

-- QUOTAS
ALTER USER "C##JARDINERIA" QUOTA UNLIMITED ON "JARDINERIA";
-- ROLES
GRANT CONNECT TO C##JARDINERIA;
GRANT RESOURCE TO C##JARDINERIA;